replicaCount: 1

image:
  repository: azureks.azurecr.io/kube-tools/features-api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "feature-api"
fullnameOverride: "feature-api"

environment:
  environmentVariables: []
  environmentSecrets:
    - name: az-client-id
      key: AZURE_CLIENT_ID
    - name: az-client-secret
      key: AZURE_CLIENT_SECRET
    - name: az-tenant-id
      key: AZURE_TENANT_ID

probes:
  endpoints:
    liveness: "/api/health/alive"
    readiness: "/api/health/ready"
  initialDelay: 15
  interval: 45
  timeout: 30
  
serviceAccount:
  create: true
  name: "feature-api"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  
resources:
  limits:
    cpu: 100m
    memory: 250Mi
  requests:
    cpu: 75m
    memory: 125Mi
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 90